tailwind.config = {
    theme: {
        extend: {
            fontFamily: {
                sans: ['Montserrat', 'sans-serif'],
                serif: ['Lora', 'serif'],
            },
            colors: {
                mantiqueira: {
                    dark: '#0a0c0a',
                    earth: '#c5a373',
                    rock: '#2c2f2e',
                    green: '#1a241a'
                }
            }
        }
    }
}